// Generated from the official map: each location's surrounding terrain colours were sampled and
// classified (snow, desert, forest, meadow, coast). See art/README or the project notes.
// "mountain" = snowy/icy ground. Keys are location slugs (the middle part of a location_uid).
extension Biome {
    static let table: [String: String] = [
        "azurazera": "mountain",
        "barbantok": "mountain",
        "beach_of_woes": "mountain",
        "bilgemont_port": "coast",
        "black_eye_peak": "mountain",
        "blackrane": "meadow",
        "blackspell_port": "coast",
        "blackwater_fields": "meadow",
        "bog_bottom": "meadow",
        "bog_top": "meadow",
        "casbrant_fields": "mountain",
        "casbrants_grave": "coast",
        "centaham": "mountain",
        "coldington": "mountain",
        "crown_of_cinders": "desert",
        "darkdepths": "coast",
        "disenchanted_forest": "mountain",
        "everhaven": "meadow",
        "farsand_coast": "coast",
        "fertile_shallows": "coast",
        "fort_of_permafrost": "mountain",
        "frostbite_mountain": "mountain",
        "frusenholm": "mountain",
        "granfiddich": "meadow",
        "granfiddich_shores": "coast",
        "halfling_campgrounds": "meadow",
        "halfmaw_hideout": "meadow",
        "horn_of_respite": "coast",
        "kallaheim": "mountain",
        "kelp_forest": "coast",
        "kildome_cross": "coast",
        "mangrove_forest": "forest",
        "myriadian_arc": "desert",
        "noiseless_pass": "mountain",
        "nomad_woods": "mountain",
        "norsack_plains": "mountain",
        "nurturing_nook_springs": "mountain",
        "old_arena_ruins": "meadow",
        "pit_of_pittance": "mountain",
        "port_skildar": "coast",
        "red_coast": "coast",
        "salsfirth": "meadow",
        "sanguine_hills": "mountain",
        "stalking_yew_woods": "forest",
        "tendon_wet_fields": "meadow",
        "underwater_cave": "coast",
        "vastalume": "coast",
        "warrenfield": "meadow",
        "winter_waves_glacier": "coast",
        "winters_end": "mountain",
        "witches_woods": "forest",
        "wraithwater": "meadow"
    ]
}
